# Generated by Django 4.0.3 on 2022-03-20 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
                ('promo_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('На прием', 'На прием'), ('Подтвержден', 'Подтвержден')], default='На прием', max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_accounts.salonservice')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_accounts.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
