# Generated by Django 4.0.3 on 2022-03-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafftimetable',
            name='time_list',
        ),
        migrations.CreateModel(
            name='TimeRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_accounts.staff')),
            ],
        ),
    ]
