# Generated by Django 4.0.3 on 2022-05-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_accounts.category'),
        ),
    ]
