# Generated by Django 4.0.3 on 2022-03-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0003_staffservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonservice',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to='business_accounts.staff'),
        ),
        migrations.DeleteModel(
            name='StaffService',
        ),
    ]
