# Generated by Django 4.0.3 on 2022-03-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_accounts', '0004_salonservice_staff_delete_staffservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salonservice',
            name='staff',
            field=models.ManyToManyField(blank=True, to='business_accounts.staff'),
        ),
    ]
